const colors={px:'#f5a16c',nx:'#e96fb4',py:'#75d88e',ny:'#d6e36f',pz:'#69bde4',nz:'#9b6de7'};
const faceNames=['px','nx','py','ny','pz','nz'];
const faceVectors={px:[1,0,0],nx:[-1,0,0],py:[0,1,0],ny:[0,-1,0],pz:[0,0,1],nz:[0,0,-1]};
const vectorFaces={'1,0,0':'px','-1,0,0':'nx','0,1,0':'py','0,-1,0':'ny','0,0,1':'pz','0,0,-1':'nz'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let size=3,mode='twist',moves=0,history=[],timerId=null,startAt=0,elapsed=0,playing=false,playIndex=0,shuffled=false;
let model=[],modelById=new Map(),cubeElements=new Map(),pointer=null,activeSlice=null,turning=false,turnTimer=null;
let viewX=-27,viewY=38,resizeTimer=null;

function blend(hex,target,amount){const val=h=>parseInt(h,16),a=hex.replace('#',''),b=target.replace('#','');return'#'+[0,2,4].map(i=>Math.round(val(a.slice(i,i+2))*(1-amount)+val(b.slice(i,i+2))*amount).toString(16).padStart(2,'0')).join('')}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function createSolvedModel(n){const next=[];let id=0;for(let x=0;x<n;x++)for(let y=0;y<n;y++)for(let z=0;z<n;z++){const stickers={};if(x===n-1)stickers.px=colors.px;if(x===0)stickers.nx=colors.nx;if(y===n-1)stickers.py=colors.py;if(y===0)stickers.ny=colors.ny;if(z===n-1)stickers.pz=colors.pz;if(z===0)stickers.nz=colors.nz;next.push({id:`c${id++}`,x,y,z,stickers})}return next}
function cubeDimension(){return window.innerWidth<680?238:window.innerWidth<1100?266:286}
function updateWorld(){const cube=$('#cubeSpace');cube.style.transform=`translate(-50%,-50%) rotateX(${viewX}deg) rotateY(${viewY}deg)`}
function renderCube3D(){
  const cube=$('#cubeSpace'),dim=cubeDimension(),unit=dim/size,gap=size<=3?2.8:size<=5?2:size<=7?1.5:1.15,piece=unit-gap,half=piece/2,center=(size-1)/2;
  cube.innerHTML='';cube.style.setProperty('--cube-dim',`${dim}px`);cubeElements.clear();modelById=new Map(model.map(c=>[c.id,c]));
  const frag=document.createDocumentFragment();
  model.forEach(c=>{
    const el=document.createElement('div');el.className='cubie';el.dataset.id=c.id;el.style.setProperty('--piece',`${piece}px`);el.style.setProperty('--half',`${half}px`);el.style.setProperty('--sticker-inset',`${Math.max(.35,piece*.012)}px`);el.style.setProperty('--sticker-radius',`${Math.max(2,Math.min(9,piece*.11))}px`);
    const tx=(c.x-center)*unit,ty=(c.y-center)*unit,tz=(c.z-center)*unit;el.style.transform=`translate3d(calc(-50% + ${tx}px),calc(-50% + ${ty}px),${tz}px)`;
    faceNames.forEach(face=>{const side=document.createElement('div');side.className=`cubie-face face-${face}`;side.dataset.face=face;side.dataset.cubieId=c.id;const color=c.stickers[face];if(color){side.classList.add('has-color');side.style.setProperty('--edge-color',blend(color,'#252942',.14));const sticker=document.createElement('span');sticker.className='sticker3d';sticker.style.background=`linear-gradient(145deg,${blend(color,'#ffffff',.58)} 0%,${blend(color,'#ffffff',.26)} 28%,${color} 62%,${blend(color,'#3d315d',.16)} 100%)`;side.appendChild(sticker)}el.appendChild(side)});
    cubeElements.set(c.id,el);frag.appendChild(el)
  });
  cube.appendChild(frag);updateWorld()
}
function rotateVector(v,axis,dir){const[x,y,z]=v;if(axis==='x')return dir>0?[x,-z,y]:[x,z,-y];if(axis==='y')return dir>0?[z,y,-x]:[-z,y,x];return dir>0?[-y,x,z]:[y,-x,z]}
function applyTurn(axis,layer,dir,turns=1){for(let count=0;count<turns;count++){const center=(size-1)/2;model.filter(c=>c[axis]===layer).forEach(c=>{const p=rotateVector([c.x-center,c.y-center,c.z-center],axis,dir);c.x=Math.round(p[0]+center);c.y=Math.round(p[1]+center);c.z=Math.round(p[2]+center);const stickers={};Object.entries(c.stickers).forEach(([face,color])=>{stickers[vectorFaces[rotateVector(faceVectors[face],axis,dir).join(',')]]=color});c.stickers=stickers})}}
function axisTransform(axis,angle){return`${axis==='x'?'rotateX':axis==='y'?'rotateY':'rotateZ'}(${angle}deg)`}
function startTimer(){if(timerId)return;startAt=performance.now()-elapsed;timerId=setInterval(()=>{elapsed=performance.now()-startAt;const sec=elapsed/1000;$('#timer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(Math.floor(sec%60)).padStart(2,'0')}.${Math.floor((sec%1)*10)}`},100)}
function stopTimer(){clearInterval(timerId);timerId=null}
function formatTime(seconds){const safe=Math.max(0,seconds),minutes=Math.floor(safe/60),secs=Math.floor(safe%60),tenth=Math.floor(safe%1*10);return`${String(minutes).padStart(2,'0')}:${String(secs).padStart(2,'0')}.${tenth}`}
function updateReview(){
  const hasRun=history.length>0||elapsed>0,actualMoves=hasRun?moves:(size===3?28:Math.round(size*size*6.1)),seconds=hasRun?Math.max(elapsed/1000,actualMoves*.2):(size===3?42.6:78.4+(size-4)*12),optimal=size===3?21:Math.round(size*size*5.4),extra=Math.max(0,actualMoves-optimal),tps=actualMoves/Math.max(seconds,1),efficiency=Math.round(Math.min(100,optimal/Math.max(actualMoves,1)*100)),pauseCount=history.slice(1).reduce((count,item,i)=>count+(item.at-history[i].at>1300?1:0),0),pauses=hasRun?pauseCount:(size===3?3:Math.max(4,size-1)),score=clamp(Math.round(96-extra*1.8-Math.max(0,seconds-(size===3?28:60))*.15-pauses*1.2),58,98);
  $('#reviewTime').textContent=formatTime(seconds);$('#reviewMoves').textContent=`${actualMoves} 步`;$('#reviewTps').textContent=`${tps.toFixed(2)} TPS`;$('#reviewEfficiency').textContent=`${efficiency}%`;$('#reviewPauses').textContent=`${pauses} 次`;
  $('#reviewHeadline').textContent=extra>0?`这次可以少走 ${extra} 步`:'本局路线已经很精简';$('#reviewSummary').textContent=hasRun?'已按本局操作轨迹分析转动效率、阶段用时和可合并动作。':'完成一次挑战后，这里会按你的实际轨迹生成完整复盘。';
  $('#scoreValue').textContent=score;$('#scoreRing').style.background=`conic-gradient(var(--blue) ${score*3.6}deg,#edf1f5 0)`;$('#scoreTitle').textContent=score>=90?'表现出色':score>=80?'节奏稳定':'还有提升空间';$('#scoreText').textContent=extra>0?`路线中有 ${extra} 步可优化，优先减少回退和重复观察。`:'动作路线紧凑，下一步可以把重点放在连贯度和预判。';
  const inversePairs=history.slice(1).reduce((count,item,i)=>count+(item.axis===history[i].axis&&item.layer===history[i].layer&&item.dir===-history[i].dir?1:0),0),redundant=hasRun?inversePairs*2:4;$('#redundantTitle').textContent=redundant?`有 ${redundant} 步可直接抵消`:'未发现直接抵消动作';$('#redundantText').textContent=redundant?'检测到相邻的逆向转动，合并后能让路线更短。':'当前转动没有紧邻回退，可继续压缩公式之间的观察停顿。';
  const stageNames=size===3?['底层十字','前两层 F2L','顶层定向','顶层排列']:['中心块','棱块配对','3×3 阶段','特殊情况'],shares=size===3?[.16,.43,.19,.22]:[.3,.34,.25,.11],maxShare=Math.max(...shares);$('#reviewStages').innerHTML=stageNames.map((name,i)=>{const stageSeconds=seconds*shares[i],width=Math.round(shares[i]/maxShare*100);return`<div class="stage-row"><strong>${name}</strong><span class="stage-track"><span class="stage-fill" style="width:${width}%"></span></span><span>${stageSeconds.toFixed(1)}s</span></div>`}).join('')
}
function updateStatus(){$('#moveCount').textContent=moves;$('#statusText').textContent=turning?'转动中':shuffled?'复原中':'已复原';updateReview()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._id);t._id=setTimeout(()=>t.classList.remove('show'),1800)}
function layerName(spec){if(spec.axis==='x')return spec.layer===size-1?'右层':spec.layer===0?'左层':`第 ${spec.layer+1} 纵层`;if(spec.axis==='y')return spec.layer===0?'顶层':spec.layer===size-1?'底层':`第 ${spec.layer+1} 横层`;return spec.layer===size-1?'正面层':spec.layer===0?'背面层':`第 ${size-spec.layer} 深层`}
function moveLabel(spec,dir,turns=1){let base;if(spec.axis==='x')base=spec.layer===size-1?'R':spec.layer===0?'L':`${spec.layer+1}R`;else if(spec.axis==='y')base=spec.layer===0?'U':spec.layer===size-1?'D':`${spec.layer+1}U`;else base=spec.layer===size-1?'F':spec.layer===0?'B':`${size-spec.layer}F`;return base+(turns===2?'2':dir<0?'′':'')}
function showTurn(label,spec,dir){$('#turnArrow').textContent=dir<0?'↺':'↻';$('#turnLabel').textContent=label;$('#turnName').textContent=`${layerName(spec)}随手势转动`;$('#turnFeedback').classList.add('show')}
function beginSlice(spec){if(turning)return false;const cube=$('#cubeSpace'),group=document.createElement('div');group.className='slice-group';cube.appendChild(group);model.filter(c=>c[spec.axis]===spec.layer).forEach(c=>{const el=cubeElements.get(c.id);if(el)group.appendChild(el)});activeSlice={...spec,group,angle:0};turning=true;startTimer();$('#cubeStage').classList.add('dragging');$('#cubeWrap').classList.add('is-turning');updateStatus();return true}
function setSliceAngle(angle,animate=false,duration=280){if(!activeSlice)return;activeSlice.angle=angle;activeSlice.group.style.transition=animate?`transform ${duration}ms cubic-bezier(.2,.82,.22,1)`:'none';activeSlice.group.style.transform=axisTransform(activeSlice.axis,angle)}
function finishSlice(){if(!activeSlice)return;const slice=activeSlice,commit=Math.abs(slice.angle)>=22,target=commit?(slice.angle<0?-90:90):0,dir=target<0?-1:1;setSliceAngle(target,true,commit?300:210);if(commit)showTurn(moveLabel(slice,dir),slice,dir);turnTimer=setTimeout(()=>{if(commit){applyTurn(slice.axis,slice.layer,dir);moves++;history.push({axis:slice.axis,layer:slice.layer,dir,turns:1,label:moveLabel(slice,dir),at:performance.now()});shuffled=true}activeSlice=null;turning=false;turnTimer=null;$('#cubeStage').classList.remove('dragging');$('#cubeWrap').classList.remove('is-turning');$('#turnFeedback').classList.remove('show');renderCube3D();updateStatus()},commit?320:230)}
function cancelTurn(rebuild=true){clearTimeout(turnTimer);turnTimer=null;activeSlice=null;turning=false;pointer=null;$('#cubeStage').classList.remove('dragging');$('#cubeWrap').classList.remove('is-turning');$('#turnFeedback').classList.remove('show');if(rebuild)renderCube3D();updateStatus()}
function specFromLabel(label){const base=label[0],prime=label.includes('′')||label.includes("'"),turns=label.includes('2')?2:1;let spec;if(base==='L')spec={axis:'x',layer:0,dir:-1};else if(base==='R')spec={axis:'x',layer:size-1,dir:1};else if(base==='U')spec={axis:'y',layer:0,dir:-1};else if(base==='D')spec={axis:'y',layer:size-1,dir:1};else if(base==='B')spec={axis:'z',layer:0,dir:-1};else spec={axis:'z',layer:size-1,dir:1};if(prime)spec.dir*=-1;return{...spec,turns}}
function performMove(label='R'){if(turning)return false;const spec=specFromLabel(label);if(!beginSlice(spec))return false;showTurn(label,spec,spec.dir);requestAnimationFrame(()=>requestAnimationFrame(()=>setSliceAngle(spec.dir*(spec.turns===2?180:90),true,spec.turns===2?460:340)));turnTimer=setTimeout(()=>{applyTurn(spec.axis,spec.layer,spec.dir,spec.turns);moves++;history.push({...spec,label,at:performance.now()});shuffled=true;activeSlice=null;turning=false;turnTimer=null;$('#cubeStage').classList.remove('dragging');$('#cubeWrap').classList.remove('is-turning');$('#turnFeedback').classList.remove('show');renderCube3D();updateStatus()},spec.turns===2?490:370);return true}
function deriveSlice(face,cubie,dx,dy){const horizontal=Math.abs(dx)>=Math.abs(dy);if(face==='pz')return horizontal?{axis:'y',layer:cubie.y,component:'x',mult:1}:{axis:'x',layer:cubie.x,component:'y',mult:-1};if(face==='nz')return horizontal?{axis:'y',layer:cubie.y,component:'x',mult:-1}:{axis:'x',layer:cubie.x,component:'y',mult:1};if(face==='px')return horizontal?{axis:'y',layer:cubie.y,component:'x',mult:-1}:{axis:'z',layer:cubie.z,component:'y',mult:1};if(face==='nx')return horizontal?{axis:'y',layer:cubie.y,component:'x',mult:1}:{axis:'z',layer:cubie.z,component:'y',mult:-1};if(face==='ny')return horizontal?{axis:'z',layer:cubie.z,component:'x',mult:1}:{axis:'x',layer:cubie.x,component:'y',mult:1};return horizontal?{axis:'z',layer:cubie.z,component:'x',mult:-1}:{axis:'x',layer:cubie.x,component:'y',mult:-1}}
function reset(){cancelTurn(false);stopTimer();elapsed=0;moves=0;history=[];shuffled=false;playIndex=0;model=createSolvedModel(size);$('#timer').textContent='00:00.0';renderCube3D();updateStatus();updatePlay();toast('魔方已复原')}
function shuffle(){cancelTurn(false);stopTimer();elapsed=0;moves=0;history=[];model=createSolvedModel(size);const axes=['x','y','z'],count=14+size*2;for(let i=0;i<count;i++){const axis=axes[Math.floor(Math.random()*3)],layer=Math.random()<.76?(Math.random()<.5?0:size-1):Math.floor(Math.random()*size),dir=Math.random()<.5?-1:1;applyTurn(axis,layer,dir)}shuffled=true;$('#timer').textContent='00:00.0';renderCube3D();updateStatus();toast(`${size}×${size} 魔方已随机打乱`)}
function setSize(n){size=n;reset();$$('.size-btn').forEach(b=>b.classList.toggle('active',+b.dataset.size===n));const high=n>3,speed=Math.round(n*n*5.4),easy=Math.round(n*n*7.2);$('#methodLabel').textContent=high?`${n}×${n} · 降阶法`:'3×3 · CFOP';$('#speedMoves').textContent=high?speed:21;$('#easyMoves').textContent=high?easy:34;$('#routeMoves').textContent=`${high?speed:21} 步`;$('#routeTime').textContent=high?`${Math.round(1.2+n*.45)} 分钟`:'18 秒';$('#routeLevel').textContent=high?'中高阶':'进阶';$('#solutionSub').textContent=high?'按中心块、棱块配对、3×3 阶段和特殊情况分步演示。':'打乱魔方后查询解法，可逐步播放并同步观察转动。';$('#focusTitle').textContent=high?'保持中心块顺序':'减少无效转体';$('#focusText').textContent=high?'先固定每一面的中心色，再成对整理棱块，避免后续阶段重新拆解。':'先预判下一组色块，再执行连续公式，避免中途反复调整观察角度。';buildPhases()}
function buildPhases(){const names=size===3?['底层十字','前两层 F2L','顶层定向 OLL','顶层排列 PLL']:['中心块复原','棱块配对','转为 3×3','特殊情况处理'],descriptions=size===3?['规划四条底棱，一次完成','配对角块与棱块，连续插入','统一顶面朝向，减少转体','调整最后一层位置并收尾']:['按固定色序从内向外拼中心','逐组配对全部棱块','使用熟悉的 3×3 路线完成','识别并处理高阶特殊情况'];$('#phaseList').innerHTML=names.map((name,i)=>`<div class="phase ${i===0?'active':''}" data-phase="${i}"><span class="phase-no">${i+1}</span><span class="phase-copy"><span class="phase-name">${name}</span><small>${descriptions[i]}</small></span><small>${[4,8,6,3][i]+(size-3)*3} 步</small></div>`).join('');updateReview()}
function querySolution(){$('[data-tab="solution"]').click();$('#solutionTitle').textContent=size===3?'已生成 3 种可练习玩法':`已生成 ${size}×${size} 降阶训练路线`;toast('推荐玩法已生成，可逐步播放')}
const algorithms={speed:['R','U','R′','U′','F′','U','F','U2','R2'],easy:['R','U','R′','U′','R','U','R′','U′'],focus:['R','U','R′','U','R','U2','R′']};
const moveEls=()=>$$('#algorithm .move');
function setAlgorithm(labels){playing=false;$('#playBtn').textContent='▶';playIndex=0;$('#algorithm').innerHTML=labels.map(label=>`<span class="move">${label}</span>`).join(' ');updatePlay()}
function updatePlay(){const total=moveEls().length;moveEls().forEach((m,i)=>m.classList.toggle('active',i===playIndex-1));$('#timelineFill').style.width=`${total?playIndex/total*100:0}%`;$('#stepLabel').textContent=`${playIndex} / ${total}`;$('#algorithmStep').textContent=`步骤 ${playIndex} / ${total}`}
function togglePlay(){const total=moveEls().length;playing=!playing;$('#playBtn').textContent=playing?'Ⅱ':'▶';if(playing){if(playIndex>=total)playIndex=0;const tick=()=>{if(!playing)return;if(playIndex>=total){playing=false;$('#playBtn').textContent='▶';toast('演示完成');return}const label=moveEls()[playIndex].textContent;if(performMove(label)){playIndex++;updatePlay()}setTimeout(tick,label.includes('2')?620:500)};tick()}}

$$('.size-btn').forEach(b=>b.onclick=()=>setSize(+b.dataset.size));
$$('.mode-btn').forEach(b=>b.onclick=()=>{if(turning)return toast('请先完成当前转动');mode=b.dataset.mode;$$('.mode-btn').forEach(x=>x.classList.toggle('active',x===b));$('#stageHint').textContent=mode==='twist'?'左键拖色块转层 · 按住滚轮拖动观察':'左键、触控或按住滚轮拖动，自由观察魔方'});
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===t));$$('.panel').forEach(p=>p.classList.remove('active'));$('#'+t.dataset.tab+'Panel').classList.add('active');if(t.dataset.tab==='review')updateReview()});
$$('.solution-card').forEach(c=>c.onclick=()=>{const method=c.dataset.method,high=size>3,speed=high?Math.round(size*size*5.4):21,easy=high?Math.round(size*size*7.2):34;$$('.solution-card').forEach(x=>x.classList.toggle('selected',x===c));setAlgorithm(algorithms[method]);if(method==='speed'){$('#routeMoves').textContent=`${speed} 步`;$('#routeTime').textContent=high?`${Math.round(1.2+size*.45)} 分钟`:'18 秒';$('#routeLevel').textContent=high?'中高阶':'进阶';toast('已选择速拧推荐')}else if(method==='easy'){$('#routeMoves').textContent=`${easy} 步`;$('#routeTime').textContent=high?`${Math.round(2+size*.65)} 分钟`:'35 秒';$('#routeLevel').textContent='入门';toast('已选择易学路线')}else{$('#routeMoves').textContent='8 轮';$('#routeTime').textContent='10 分钟';$('#routeLevel').textContent='专项';toast('已选择薄弱阶段专项')}});
$('#phaseList').onclick=e=>{const phase=e.target.closest('.phase');if(!phase)return;$$('#phaseList .phase').forEach(x=>x.classList.toggle('active',x===phase));const title=phase.querySelector('.phase-name').textContent,tip=phase.querySelector('.phase-copy small').textContent,phaseAlgorithms=[['F','R','U','R′','U′','F′'],['U','R','U′','R′'],['F','R','U','R′','U′','F′'],['R','U','R′','U','R','U2','R′']];$('#focusTitle').textContent=`专项：${title}`;$('#focusText').textContent=tip;setAlgorithm(phaseAlgorithms[+phase.dataset.phase]);toast(`已切换到${title}练习`)};
$('#shuffleBtn').onclick=shuffle;$('#resetBtn').onclick=reset;$('#solveBtn').onclick=querySolution;$('#playBtn').onclick=togglePlay;$('#guideBtn').onclick=()=>toast('左键拖色块转层；按住鼠标滚轮拖动可随时观察视角');
$('#undoBtn').onclick=()=>{if(turning)return toast('请等待当前转动完成');const last=history.pop();if(!last)return toast('还没有可撤销的操作');applyTurn(last.axis,last.layer,-last.dir,last.turns||1);moves=Math.max(0,moves-1);renderCube3D();updateStatus();toast('已撤销上一步')};
$('#optimizedReplayBtn').onclick=()=>{$('[data-tab="solution"]').click();const speedCard=$('[data-method="speed"]');$$('.solution-card').forEach(x=>x.classList.toggle('selected',x===speedCard));setAlgorithm(algorithms.speed);togglePlay();toast('正在按优化路线重放')};
$('#retryBtn').onclick=()=>{shuffle();$('[data-tab="solution"]').click();toast('已重新打乱，开始下一局挑战')};

const stage=$('#cubeStage');
stage.addEventListener('pointerdown',e=>{if(turning)return;const middle=e.pointerType==='mouse'&&e.button===1;if(e.pointerType==='mouse'&&e.button!==0&&!middle)return;if(middle)e.preventDefault();const gestureMode=middle?'orbit':mode,face=e.target.closest?.('.cubie-face');if(gestureMode==='twist'&&!face)return;pointer={x:e.clientX,y:e.clientY,startViewX:viewX,startViewY:viewY,face:face?.dataset.face,cubieId:face?.dataset.cubieId,spec:null,gestureMode};stage.setPointerCapture?.(e.pointerId);stage.classList.add('dragging')});
stage.addEventListener('pointermove',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(pointer.gestureMode==='orbit'){viewY=pointer.startViewY+dx*.32;viewX=clamp(pointer.startViewX-dy*.28,-62,22);updateWorld();return}if(!pointer.spec&&Math.hypot(dx,dy)>7){const cubie=modelById.get(pointer.cubieId);if(!cubie)return;pointer.spec=deriveSlice(pointer.face,cubie,dx,dy);beginSlice(pointer.spec)}if(pointer.spec&&activeSlice){const delta=pointer.spec.component==='x'?dx:dy,angle=clamp(delta*pointer.spec.mult*.78,-108,108);setSliceAngle(angle);const dir=angle<0?-1:1;showTurn(moveLabel(pointer.spec,dir),pointer.spec,dir)}});
stage.addEventListener('pointerup',()=>{if(!pointer)return;if(pointer.gestureMode==='twist'&&activeSlice)finishSlice();else stage.classList.remove('dragging');pointer=null});
stage.addEventListener('auxclick',e=>{if(e.button===1)e.preventDefault()});
stage.addEventListener('pointercancel',()=>{if(activeSlice){setSliceAngle(0,true,180);setTimeout(()=>cancelTurn(),190)}else{stage.classList.remove('dragging');pointer=null}});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();shuffle()}if(e.key.toLowerCase()==='r')performMove(e.shiftKey?'R′':'R');if(e.key.toLowerCase()==='u')performMove(e.shiftKey?'U′':'U')});
window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!turning)renderCube3D()},120)});

model=createSolvedModel(size);buildPhases();renderCube3D();updatePlay();updateStatus();
if(document.modelContext?.registerTool){const lifecycle=new AbortController(),register=tool=>Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});register({name:'set_cube_size',title:'选择魔方阶数',description:'将训练台切换为 3×3 到 9×9 之间的指定阶数。',inputSchema:{type:'object',properties:{size:{type:'integer',minimum:3,maximum:9}},required:['size'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!Number.isInteger(input?.size)||input.size<3||input.size>9)throw new Error('阶数必须是 3 到 9 的整数');setSize(input.size);return{size,status:'ready'}}});register({name:'scramble_cube',title:'打乱魔方',description:'按当前阶数打乱魔方并准备开始计时。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){shuffle();return{size,status:'scrambled'}}});register({name:'query_solution',title:'查询推荐解法',description:'为当前魔方状态打开推荐解法，并返回当前采用的解法类型。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){querySolution();return{size,method:size===3?'CFOP':'reduction',prototype:true}}})}
